/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>

int main(void){

	//++++++++ 1.0 Ejemplo básico punteros    +++++++++++++

	//Definimos variables
	uint8_t dato = 124;

	//Creamos un puntero con la dirección de memoria de la var
	uint8_t *pDato = &dato;

	//Guardar el valor que esta en esa dirección de memoria
//	uint8_t valorDato = *pDato;

	//Casteo básico
//	uint16_t casteoDato = (uint16_t) dato;

	/* Lo que no se debe hacer */
	//Crear un puntero en una dirección específica

	//Creamos un puntero que me apunta a una variable de 16 bits.La dirección es un número de 32 bits
	//entonces hay que decirle al sistema que es una dirección de memoria que me apunta una variable de 16 bits.
	//Es decir, pasamos de un número a un puntero
	uint16_t *punteroDireccion = (uint16_t *)0x20000001;   //Dirección tomada de la imagen memory mapping

	//Cambiar dirección de memoria del puntero
	punteroDireccion = (uint16_t *) 0x20000002;

	//Guardar la dirección de memoria de un puntero
	//Pasamos de un puntero a un número de 32 bits
//	uint32_t direccionDato = (uint32_t) pDato;

	//Cambiar el valor almacenado en el puntero
	*pDato = 200;

	//Aumentar 8 bits el puntero
	pDato++;

	//++++++++++   2.0 Ejemplo arreglos   ++++++++++++

	#define sizeOfArray 4
	uint8_t miPrimerArreglo[sizeOfArray] = {5, 0xAE, 'a', 254};

	//2.1 Recorrer un arreglo con ciclos
	uint8_t contenido = 0;

	for(uint8_t i=0; i<sizeOfArray; i++){
		contenido = miPrimerArreglo[i];
	}

	for(uint8_t i=0; i<sizeOfArray; i++){
			contenido = *(miPrimerArreglo+i);   //Accedo uno a uno
	}

	//Cambiar elementos de un arreglo
	miPrimerArreglo[1] = 12;
	*(miPrimerArreglo + 1) = 12;

	//+++++++++ 3.0 Estructuras ++++++++++++

	//Definicion

	typedef struct{
			uint8_t elemento1;           //Plantilla de la estructura para indicar los
			uint16_t elemento2;          //tipos de datos
			uint8_t arreglo[sizeOfArray];
	}miPrimeraEstructura;

	miPrimeraEstructura estructuraEjemplo = {0};   //Creo la estructura porque lo asigno a una variable
												   //La estructura sería estructuraEjemplo

	//Acceder a los elementos de la estructura
	estructuraEjemplo.elemento1 = 'F';
	estructuraEjemplo.elemento2 = 10;

	//Crear un puntero que apunte a la estructura

	miPrimeraEstructura *ptrMiPrimeraEstructura = &estructuraEjemplo;


	ptrMiPrimeraEstructura->elemento1 = 9;
	ptrMiPrimeraEstructura->arreglo[2] = 15;










}


