/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>

#include "GPIOxDriver.h"

#define SUMA '+'
#define RESTA '-'
#define MULTIPLICACION '*'
#define DIVISION '/'
#define FACTORIAL '!'
#define FIBONACCI 'F'

//Funcion switch case

uint16_t resultadoOperacion(uint8_t tipoDeOperacion,uint8_t numeroA, uint8_t numeroB){
	uint16_t resultado = 0;

	switch (tipoDeOperacion){
	case SUMA:
	{
		resultado= numeroA + numeroB;
		break;
	}
	case RESTA:
	{
		resultado= numeroA - numeroB;
		break;
	}
	default:
	{
		resultado = 0;
		break;
	}
	}
	return resultado;
}


int main(void){

	//uint16_t operacionFinal = 0;
	//operacionFinal = resultadoOperacion (SUMA, 7, 10);
	//operacionFinal++;

}

uint32_t resultadoOperaciones(uint8_t tipoDeOperacion, uint8_t numero){
	uint16_t contador = numero;
	uint16_t resultado = 1;

	switch (tipoDeOperacion){
	case FACTORIAL:
	{
		while (contador>0){

			resultado *= contador;
			contador --;
		}
		break;
	}
	case FIBONACCI:
	{
		while (contador<numero){
			contador++;
		}
		break;
	}
	default:
	{
		resultado = 0;
		break;
	}
	}
	return resultado;
}







