/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>
#include "stm32f411xx_hal.h"


int main(void)
{
	//Congiguración inicial del MCU
	RCC->AHB1ENR  &= -(1 << 0);  //Limpiando la posición 0 del registro
	RCC->AHB1ENR |= (1 << 0);  //Activamos la señal de reloj del GPIOA

	//Configuramos el pin PA5 como salida
	GPIOA->MODER &= -(0b11 << 10);     //Limpiamos las posiciones 11:10 del MODER
	GPIOA->MODER |= (0b01 << 10);     // Configurando el pinA5 como salida

	//Configuración OTYPE
	GPIOA->OTYPER &= -(1 << 5); //limpiamos la posición, configuración push-pull

	//Configuración OSPEED
	GPIOA->OSPEEDR &= -(0b11 << 10);     //Limpiamos posiciones 11:10
	GPIOA->OSPEEDR |= (0b10 << 10);     //Velocidad de salida en Fast

	//Configuración de las resistencias de PU-PD
	GPIOA->PUPDR &= -(0b11 << 10);    //Limpiamos las posiciones 11:10, no-PUPD

	GPIOA->ODR &= -(1 << 5);       //Limpiamos la salida PA5, apaga el led
	GPIOA->ODR |= (1 << 5);       //Enciende el LED


    /* Loop forever */
	while(1){

	}
	return 0;
}
